set ( SETTINGS_PROJECT_NAME "Example" )
set ( SETTINGS_BINARY_NAME  "Example-Game" )
set ( SETTINGS_GAME_TITLE    "${SETTINGS_PROJECT_NAME}" )

if ( "${SETTINGS_PROJECT_NAME}" EQUAL "${SETTINGS_BINARY_NAME}" )
	message ( FATAL_ERROR "SETTINGS_PROJECT_NAME must differ from SETTINGS_BINARY_NAME" )
endif()
