name: Packaging

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_DIR: ${{github.workspace}}/vsbuild

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.9
      with:
        cmake-version: '3.19.5'

    - name: Use cmake
      run: cmake --version
    
    - name: Bootstrap
      run: |
        bootstrap.bat
      shell: cmd

    - name: Configure CMake
      run: |
        mkdir "${{env.BUILD_DIR}}"
        cd "${{env.BUILD_DIR}}"
        cmake ..
      shell: cmd
      
    - name: Pack
      working-directory: ${{env.BUILD_DIR}}
      run: cpack
      
    - name: Store artifact
      uses: actions/upload-artifact@v2
      with:
        name: dgm-sdk
        path: ${{env.BUILD_DIR}}/*.zip
        retention-days: 5

  build_released_template:
    name: Build released template
    needs: build
    runs-on: windows-latest
    steps:
      - name: Download release artifact
        uses: actions/download-artifact@v2

      - name: Unzip artifact
        working-directory: ${{github.workspace}}/dgm-sdk
        run: 7z x *.zip

      - name: Build template
        working-directory: ${{github.workspace}}/dgm-sdk
        run: |
          cd dgm-sdk*
          cd project-template
          MakeRelease.bat
        shell: cmd
